/* WARNING: This file is auto-generated by build.rs */
/* DO NOT MODIFY THIS FILE DIRECTLY (your changes will not be saved! */
/* also, this type annotation was so annoying to write */
pub fn get_cmds() -> impl Fn(tauri::Invoke<tauri::Wry>) + Send + Sync + 'static {
    return tauri::generate_handler![];
}