// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
#![allow(non_snake_case)]
#![allow(dead_code)]

use MIDIAnimator::structures::ipc;
use MIDIAnimator::ui::menu;

use tauri::generate_context;

#[tokio::main]
async fn main() {
    ipc::start_server();

    let context = generate_context!();

    tauri::Builder::default()
    .invoke_handler(MIDIAnimator::auto_commands::get_cmds())  // AUTO GENERATED BY build.rs
    .menu(menu::build_menu(&context.package_info().name))
    .on_menu_event(|event| {
        menu::handle_menu_event(event);
    })
    .run(context)
    .expect("error while launching MIDIAnimator!");
}