// utils/gm_instrument_map.rs

use std::collections::HashMap;
use lazy_static::lazy_static;

// https://docs.rs/lazy_static/latest/lazy_static/
// initializing a static hashmap will need to use lazy_static
lazy_static! {
    pub static ref GM_INST: HashMap<i32, &'static str> = HashMap::from([
        (0, "Acoustic Grand Piano"),
        (1, "Bright Acoustic Piano"),
        (2, "Electric Grand Piano"),
        (3, "Honkytonk Piano"),
        (4, "Electric Piano 1"),
        (5, "Electric Piano 2"),
        (6, "Harpsichord"),
        (7, "Clavinet"),
        (8, "Celesta"),
        (9, "Glockenspiel"),
        (10, "Music Box"),
        (11, "Vibraphone"),
        (12, "Marimba"),
        (13, "Xylophone"),
        (14, "Tubular Bells"),
        (15, "Dulcimer (Santur),"),
        (16, "Drawbar Organ (Hammond),"),
        (17, "Percussive Organ"),
        (18, "Rock Organ"),
        (19, "Church Organ"),
        (20, "Reed Organ"),
        (21, "Accordion (French),"),
        (22, "Harmonica"),
        (23, "Tango Accordion (Band neon),"),
        (24, "Acoustic Guitar (nylon),"),
        (25, "Acoustic Guitar (steel),"),
        (26, "Electric Guitar (jazz),"),
        (27, "Electric Guitar (clean),"),
        (28, "Electric Guitar (muted),"),
        (29, "Overdriven Guitar"),
        (30, "Distortion Guitar"),
        (31, "Guitar harmonics"),
        (32, "Acoustic Bass"),
        (33, "Electric Bass (fingered),"),
        (34, "Electric Bass (picked),"),
        (35, "Fretless Bass"),
        (36, "Slap Bass 1"),
        (37, "Slap Bass 2"),
        (38, "Synth Bass 1"),
        (39, "Synth Bass 2"),
        (40, "Violin"),
        (41, "Viola"),
        (42, "Cello"),
        (43, "Contrabass"),
        (44, "Tremolo Strings"),
        (45, "Pizzicato Strings"),
        (46, "Orchestral Harp"),
        (47, "Timpani"),
        (48, "String Ensemble 1 (strings),"),
        (49, "String Ensemble 2 (slow strings),"),
        (50, "SynthStrings 1"),
        (51, "SynthStrings 2"),
        (52, "Choir Aahs"),
        (53, "Voice Oohs"),
        (54, "Synth Voice"),
        (55, "Orchestra Hit"),
        (56, "Trumpet"),
        (57, "Trombone"),
        (58, "Tuba"),
        (59, "Muted Trumpet"),
        (60, "French Horn"),
        (61, "Brass Section"),
        (62, "SynthBrass 1"),
        (63, "SynthBrass 2"),
        (64, "Soprano Sax"),
        (65, "Alto Sax"),
        (66, "Tenor Sax"),
        (67, "Baritone Sax"),
        (68, "Oboe"),
        (69, "English Horn"),
        (70, "Bassoon"),
        (71, "Clarinet"),
        (72, "Piccolo"),
        (73, "Flute"),
        (74, "Recorder"),
        (75, "Pan Flute"),
        (76, "Blown Bottle"),
        (77, "Shakuhachi"),
        (78, "Whistle"),
        (79, "Ocarina"),
        (80, "Lead 1 (square wave),"),
        (81, "Lead 2 (sawtooth wave),"),
        (82, "Lead 3 (calliope),"),
        (83, "Lead 4 (chiffer),"),
        (84, "Lead 5 (charang),"),
        (85, "Lead 6 (voice solo),"),
        (86, "Lead 7 (fifths),"),
        (87, "Lead 8 (bass + lead),"),
        (88, "Pad 1 (new age Fantasia),"),
        (89, "Pad 2 (warm),"),
        (90, "Pad 3 (polysynth),"),
        (91, "Pad 4 (choir space voice),"),
        (92, "Pad 5 (bowed glass),"),
        (93, "Pad 6 (metallic pro),"),
        (94, "Pad 7 (halo),"),
        (95, "Pad 8 (sweep),"),
        (96, "FX 1 (rain),"),
        (97, "FX 2 (soundtrack),"),
        (98, "FX 3 (crystal),"),
        (99, "FX 4 (atmosphere),"),
        (100, "FX 5 (brightness),"),
        (101, "FX 6 (goblins),"),
        (102, "FX 7 (echoes, drops),"),
        (103, "FX 8 (scifi, star theme),"),
        (104, "Sitar"),
        (105, "Banjo"),
        (106, "Shamisen"),
        (107, "Koto"),
        (108, "Kalimba"),
        (109, "Bag pipe"),
        (110, "Fiddle"),
        (111, "Shanai"),
        (112, "Tinkle Bell"),
        (113, "Agogo"),
        (114, "Steel Drums"),
        (115, "Woodblock"),
        (116, "Taiko Drum"),
        (117, "Melodic Tom"),
        (118, "Synth Drum"),
        (119, "Reverse Cymbal"),
        (120, "Guitar Fret Noise"),
        (121, "Breath Noise"),
        (122, "Seashore"),
        (123, "Bird Tweet"),
        (124, "Telephone Ring"),
        (125, "Helicopter"),
        (126, "Applause"),
        (127, "Gunshot")
    ]);

    pub static ref GM_PERC_INST_NOTES: HashMap<i32, &'static str> = HashMap::from([
        (35, "Acoustic Bass Drum"),
        (36, "Bass Drum 1"),
        (37, "Side Stick"),
        (38, "Acoustic Snare"),
        (39, "Hand Clap"),
        (40, "Electric Snare"),
        (41, "Low Floor Tom"),
        (42, "Closed Hi Hat"),
        (43, "High Floor Tom"),
        (44, "Pedal Hi-Hat"),
        (45, "Low Tom"),
        (46, "Open Hi-Hat"),
        (47, "Low-Mid Tom"),
        (48, "Hi Mid Tom"),
        (49, "Crash Cymbal 1"),
        (50, "High Tom"),
        (51, "Ride Cymbal 1"),
        (52, "Chinese Cymbal"),
        (53, "Ride Bell"),
        (54, "Tambourine"),
        (55, "Splash Cymbal"),
        (56, "Cowbell"),
        (57, "Crash Cymbal 2"),
        (58, "Vibraslap"),
        (59, "Ride Cymbal 2"),
        (60, "Hi Bongo"),
        (61, "Low Bongo"),
        (62, "Mute Hi Conga"),
        (63, "Open Hi Conga"),
        (64, "Low Conga"),
        (65, "High Timbale"),
        (66, "Low Timbale"),
        (67, "High Agogo"),
        (68, "Low Agogo"),
        (69, "Cabasa"),
        (70, "Maracas"),
        (71, "Short Whistle"),
        (72, "Long Whistle"),
        (73, "Short Guiro"),
        (74, "Long Guiro"),
        (75, "Claves"),
        (76, "Hi Wood Block"),
        (77, "Low Wood Block"),
        (78, "Mute Cuica"),
        (79, "Open Cuica"),
        (80, "Mute Triangle"),
        (81, "Open Triangle")
    ]);
}